version: "3"
services:
  postgres:
    image: postgres:13.13
    container_name: ass2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ass2
    volumes:
      - data:/var/lib/postgresql/data
      - ./ass2.dump.sql:/docker-entrypoint-initdb.d/ass2.dump.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ad@org.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_config:/etc/pgadmin

volumes:
  data:
    driver: local
  pgadmin_data:
    driver: local
  pgadmin_config:
    driver: local
